apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.instaxprinter'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
    namespace "expo.modules.instaxprinter"
    compileSdk safeExtGet("compileSdkVersion", 34)

    defaultConfig {
        minSdkVersion safeExtGet("minSdkVersion", 24)
        targetSdkVersion safeExtGet("targetSdkVersion", 34)
    }

    sourceSets {
        main {
            java.srcDirs = ["src/main/java"]
        }
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${getKotlinVersion()}"
}
